### ISSUE TITLE
Is Yandex inflector closed?

### ISSUE THREAD

**Issue by installero** [yaroslav/yandex_inflect#2]
The [Inflector](http://nano.yandex.ru/project/inflect/) page redirects to Yandex main page. It seems that the project is no longer available.

Are there any other solutions?

**Comment by yaroslav** [comment]
Webpage is closed, but the service itself still seem to work. I have no idea if nano.yandex.ru did move somewhere (googling does not help) — if anything, I can replace the link.

**Comment by installero** [comment]
> service itself still seem to work

Does it? That's great than! Thanks for the reply.

**Comment by denispeplin** [comment]
It is better to just remove links to nano from README for now. Having that links is VERY confusing. I thought that service is not working, but decided to try... success!

Thank a lot for great gem!
